### ISSUE TITLE
DataLoader & Context

### ISSUE THREAD

**Issue by jycouet** [graphql-hive/envelop#1026]
▶ **Is your feature request related to a problem? Please describe.**
My context is growing a lot with all my DataLoaders. 
And since everything is typed _(Yeah 🎉)_ I have a huge autocompletion flat list.

Today I have:
```
ctx
├─ req
├─ db
├─ ...
├─ dataloaderUserX
├─ dataloaderUserY
├─ dataloaderUserZ
├─ dataloaderCaseX
├─ dataloaderCaseY
├─ dataloaderCaseY
```

▶ **Describe the solution you'd like**
I would like to nest my Dataloaders into objects, something like:
```
ctx
├─ req
├─ db
├─ ...
└─ dataloader
    ├─ user
    │   ├─ X
    │   ├─ Y
    │   └─ Z
    └─ case
         ├─ X
         ├─ Y
         └─ Z
```
Like this it's easy to navigate where I want 👌.

▶ **Describe alternatives you've considered**
Maybe a single level is already sufficient:
```
ctx
├─ req
├─ db
├─ ...
└─ dataloader
    ├─ userX
    ├─ userY
    ├─ userZ
    ├─ caseX
    ├─ caseY
    └─ caseZ
```
It look like adding the dataloader element here: https://github.com/dotansimha/envelop/blob/main/packages/plugins/dataloader/src/index.ts#L14

What's your opinion ❔

▶ **Additional context**
I'm using Dataloaders in combinaison with [graphql-ez](https://www.graphql-ez.com/docs) and [graphql-modules](https://www.graphql-modules.com/) and it's simply AWESOME 😎

**Comment by dotansimha** [comment]
@jycouet maybe we can support something like this? what do you think? 

```ts
useDataLoader('dataloader.users.a', context => new DataLoader(keys => myBatchGetUsers(keys))),
```

**Comment by jycouet** [comment]
Will it splits in object? or it will be a string with `.`?

- If it splits in object, it's eaxctly what I would like
- If it's only a string with `.`, I do already `dataloader_users_a` and it's sufficient.

**Comment by jycouet** [comment]
For info @dotansimha , I'm using now `useExtendContext` and was able to have the structure I want for my dataloaders.
So it could be a nice enhancement in `useDataLoader`, but not sure it's very usefull!

I close the issue now as I have a good working solution.

**Comment by sraka1** [comment]
@dotansimha facing the same issue as the original poster. Would you accept a PR with the dot notation as you mentioned in the earlier comment?

Or should I go the more manual `useExtendContext` route?
