### ISSUE TITLE
apollo-server-express and response-cache plugin error

### ISSUE THREAD

**Issue by AzSiAz** [graphql-hive/envelop#1081]
response-cache plugin doesn't seem to work, or I am doing something wrong...
I am also use nexus

Error
```
[useResponseCache] Failed extracting document string from the context. The response will not be cached or served from the cache. If you are overriding the 'parse' behavior make sure to pass a custom 'getDocumentStringFromContext' function for getting the document string, which is required for building the response cache key.
```

Usage
```js
const getEnveloped = envelop({
        plugins: [
            useSchema(schema),
            useGraphQlJit({ customJSONSerializer: true }),
            useValidationCache(),
            useParserCache(),
            useResponseCache({
                ttlPerSchemaCoordinate: {
                    'Query.countries': 10_000,
                }
             }),
        ],
    })

const server = new ApolloServer({
        schema,
        executor: async ({ document, request: { variables, http }, operationName }) => {
            const authorization = http?.headers.get('authorization') ?? ''
            const { schema, execute, contextFactory } = getEnveloped(createContext({ authorization }))

            return execute({
                schema,
                document: document,
                contextValue: await contextFactory(),
                variableValues: variables,
                operationName: operationName,
            })
        },
        introspection,
        // plugins: [createPrometheusExporterPlugin({ app })],
    })
```

**Comment by n1ru4l** [comment]
@AzSiAz apollo-server, unfortunately, does not allow proving a custom parse and validate function, which is currently a requirement for using the response cache plugin (`useValidationCache` and `useParserCache`) won't have an impact here as well :/

We are currently investigating how we can address this issue (with manual patching apollo-server with patch-package or similar). 

Upvoting this discussion might also help find a stable long term solution for this https://github.com/apollographql/apollo-server/discussions/5541

If we cannot find a proper solution it might be worth not using apollo-server... Is there any feature that blocks you from using one of the other setups on our integrations? https://www.envelop.dev/docs/integrations

**Comment by AzSiAz** [comment]
That's what I thought too, but I was not sure, thanks for the clarification 👍 

I was planning to get rid of apollo-server eventually, seem like I will do so sooner than later

Anyway thanks for the answer and have a nice day 😃
