### ISSUE TITLE
useResponseCache crypto module usage

### ISSUE THREAD

**Issue by n1ru4l** [graphql-hive/envelop#1084]
The response cache plugin currently uses the crypto module for generating hashes which is only available on Node.js. For true cross platform we should investigate alternatives.

**Comment by n1ru4l** [comment]
https://github.com/FormidableLabs/urql/blob/477fa16800b858bdd1b9c38ecaceef1f93d968ae/exchanges/persisted-fetch/src/sha256.ts#L1-L86

This might be useful 👀

**Comment by dotansimha** [comment]
Fixed in `@envelop/response-cache@0.6.0`.
