### ISSUE TITLE
Redis response cache will halt the server if resolver return nullable type

### ISSUE THREAD

**Issue by saihaj** [graphql-hive/envelop#1090]
**Describe the bug**
There are cases when the mutation can return `null` in that case current implementation of redis-response cache will throw an error.

**To Reproduce**
https://github.com/saihaj/redis-response-cache-del-bug

**Expected behavior**

It shouldn't halt the server, just do not try to invalidate non-existent values.

**Comment by n1ru4l** [comment]
This should be as easy as checking whether the array includes any elements before passing it to the dek call.

**Comment by dotansimha** [comment]
Fixed in `@envelop/response-cache-redis@0.1.4`
