### ISSUE TITLE
Improve ergonomics around context factory typing

### ISSUE THREAD

**Issue by klippx** [graphql-hive/envelop#1101]
Typing context factory is a bit clunky since `currentContext` is hardcoded to `unknown`:

![Screenshot 2021-12-15 at 09 32 01](https://user-images.githubusercontent.com/2785359/146151582-f617eb49-5b5b-4ca4-ae46-7af81bca7eab.png)

We are writing a server library based on envelop, and we provide a few things in context out of the box to userland services. We have a priori knowledge that we will already have extended context with `req`, `correlationId` and `logger`.

**Comment by dotansimha** [comment]
Keeping open until we'll cut a release.

**Comment by dotansimha** [comment]
Available in `@envelop/core@1.6.5`, thanks @klippx
