### ISSUE TITLE
Apollo server errors plugin documentation mismatch

### ISSUE THREAD

**Issue by ivandotv** [graphql-hive/envelop#1152]
Currently, the [docs](https://www.envelop.dev/plugins/use-apollo-server-errors#usage-example) state that we should use the `formatError` key for custom error formatting, which is the same as in `apollo`. However actual code implementation expects the `formatter` key.

So either the docs should be updated, or the code should be changed to use `formatError` key.
```js
//docs
const getEnveloped = envelop({
  plugins: [
    // ... other plugins ...
    useApolloServerErrors({ 
      debug: true, /
      formatError: () => ... //  -> this is "formatter" in source
    }),
  ],
});
```
I'm willing to make a pull request.

**Comment by YassinEldeeb** [comment]
Hey, sorry for being late on this.

Good catch! We've updated our docs to match up with the `formatter` method.
