### ISSUE TITLE
Rate limiter plugin documentation mismatch

### ISSUE THREAD

**Issue by ivandotv** [graphql-hive/envelop#1153]
In the [docs](https://www.envelop.dev/plugins/use-rate-limiter#usage-example)  `identityFn` is  `async` however that is not the case in the source code.
```ts
// docs
import { useRateLimiter, IdentifyFn } from '@envelop/rate-limiter';

const identifyFn: IdentifyFn = async context => {
  return context.request.ip;
};
```
```ts
// source
export type IdentifyFn<ContextType = unknown> = (context: ContextType) => string;
```

https://github.com/dotansimha/envelop/blob/8e365c2bdeb51b0fc76d5937ab80c95c2b712bac/packages/plugins/rate-limiter/src/index.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L9

Documentation should be updated to reflect that.

**Comment by YassinEldeeb** [comment]
Hey, thanks again for catching this typo in the documentation.

It's now fixed.
