### ISSUE TITLE
[Sentry] Expose event id

### ISSUE THREAD

**Issue by Jomik** [graphql-hive/envelop#1340]
**Is your feature request related to a problem? Please describe.**

We would like to expose the sentry event id to our client so that we can better connect user reported errors with those in sentry.

**Describe the solution you'd like**
Expose `eventId` in the error extensions.

**Describe alternatives you've considered**
Not really sure, I added it in my fork when creating #1331

**Additional context**

I already have a working implementation I will be happy to create a PR with.
What should the extension key be called? Should it be customisable? What are your requirements?

**Comment by n1ru4l** [comment]
I really like this idea!

Something like `sentryEventId`

We could also go for something like

```
sentry: {
  eventId: "..."
}
```

If there are more sentry extension values added in the future, any thoughts?

**Comment by Jomik** [comment]
Yeah, that can make sense! I am unsure what values it would be though.
The benefit of having it be 'flat', is that we could expose an option for the user `eventKey: string = 'sentryEventId'` .
I will open a PR with this, if you will tell me what structure to use for the extension.
Personally we avoid mentioning Sentry, as our client should not care about source, they can just forward this to our developers. 😄
