### ISSUE TITLE
[useSentry] @sentry/ >= 6.18.x causes runtime error

### ISSUE THREAD

**Issue by AzSiAz** [graphql-hive/envelop#1342]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please makee sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**
While refactoring my code to use Pothos, I noticed using `@envelop/sentry` result in 
```JSON
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'setData')"
    }
  ]
}
```

**To Reproduce**
Just use sentry plugin with Pothos framework, exemple repo
https://stackblitz.com/edit/node-qabanz?file=package.json

**Expected behavior**
No Error

**Environment:**

- OS: `MacOS`
- NodeJS: `17` & `16`
- `@envelop/sentry`: `3.1.1`
- `@envelop/core`: `2.1.0`

**Additional context**
I am also using this as server 
`@graphql-ez/express`: `0.9.7`,
`@graphql-ez/plugin-websockets`: `0.10.4`,

**Comment by MattiaPette** [comment]
Hi, I've noticed the same error in my local environment (a simple test project using envelop + sentry), and downgrading    `@sentry/node` and `@sentry/tracing` to `6.18.1` fixed this for me, the version `6.18.2` doesn't work so the bug may be related to that particular version.

**Comment by AzSiAz** [comment]
I am also using the latest version of sentry, but I didn't notice any problem with nexus :thinking: 
I will try later today just in case i missed it

If downgrading sentry is the way to temporary fix this, then perfect I will just wait until upgrading it again until a fix is issued

**Comment by AzSiAz** [comment]
I tested with `6.18.1` for sentry package and `3.1.1` for `@envelop/sentry` and it's working as @MattiaPette said

**Comment by n1ru4l** [comment]
Hey, I updated the issue with the workflow progress for resolving it.

**Comment by AzSiAz** [comment]
I edited my post with a reproduction

**Comment by n1ru4l** [comment]
I reduced the reproduction further in https://stackblitz.com/edit/node-kwtsm9?file=src/index.ts

This is not related to pothos at all. I will update the title of this issue.

**Comment by AzSiAz** [comment]
True, thanks for the update

**Comment by pi0neerpat** [comment]
In case anyone else encounters this in a RedwoodJS project, hre's what worked for me after nuking node_modules, yarn.lock, and /dist.

```json
    "@envelop/rate-limiter": "^1.0.0",
    "@envelop/sentry": "^3.1.1",
    "@redwoodjs/api": "^0.50.0",
    "@redwoodjs/graphql-server": "^0.50.0",
    "@sentry/node": "6.18.1",
    "@sentry/tracing": "6.18.1",
```

**Comment by HashDot** [comment]
I have the same problem with the following packages:
```json
    "@envelop/graphql-jit": "^4.1.0",
    "@envelop/sentry": "^3.1.1",
    "@graphql-yoga/node": "^2.0.0",
    "@sentry/node": "^6.18.1",
    "@sentry/tracing": "^6.18.1",
```
I tested it with the latest versions and with this downgrade fix. Nothing works.

**Comment by n1ru4l** [comment]
@HashDot `^6.18.1` will resolve to `6.19.3`. You need to pin to the exact version `6.18.1`.

See https://semver.npmjs.com/ for more information as well as https://docs.npmjs.com/about-semantic-versioning


In regards to fixing this issue, it seems like there is an unexpected breaking change within sentry. I quickly scanned the sentry issues but could not find one. I will dedicate more time to this issue next week. In the meantime, any help or research (of the sentry changes) is highly appreciated.

**Comment by HashDot** [comment]
@n1ru4l ty. my bad :)

**Comment by n1ru4l** [comment]
This is linked to https://github.com/getsentry/sentry-javascript/issues/4731

I created https://github.com/dotansimha/envelop/pull/1367 with a failing test.

Currently, a workaround seems to be adding a `import "@sentry/tracing"`.

**Comment by n1ru4l** [comment]
@HashDot @AzSiAz @pi0neerpat @MattiaPette can anyone confirm whether this is solved with sentry version `6.19.4` https://github.com/getsentry/sentry-javascript/issues/4731#issuecomment-1103497196?

**Comment by MattiaPette** [comment]
Hi @n1ru4l !
I've updated to @envelop/core@^2.3.1, @envelop/sentry@^3.4.0, @sentry/node@^6.19.6, @sentry/tracing@^6.19.6 and it's not causing any runtime errors in my project in the limited testing i've done.

Version 6.19.4 works as well with the same results.

Only thing that I'm noticing has changed right now is this log:
```
Sentry Logger [log]: Integration installed: InboundFilters
Sentry Logger [log]: Integration installed: FunctionToString
Sentry Logger [log]: Integration installed: ContextLines
Sentry Logger [log]: Integration installed: Console
Sentry Logger [log]: Integration installed: OnUncaughtException
Sentry Logger [log]: Integration installed: OnUnhandledRejection
Sentry Logger [log]: Integration installed: LinkedErrors
Sentry Logger [log]: Integration installed: Http
Sentry Logger [error]: Mongo Integration was unable to require `mongodb` package.
Sentry Logger [log]: Integration installed: Mongo
```
It's probably not related to this issue, will try to investigate further and open another issue if it's needed.

**Comment by AzSiAz** [comment]
Still need to import `import '@sentry/tracing'` as soon as I use `useSentry` from `@envelop/sentry` (v3.4.0) and I make a query
No bundler on my side just `ts-node-dev` and `tsc` to build production version
Tested with `@sentry/node` & `@sentry/tracing` version 6.19.4 and 6.19.6 (with fresh node module install)

**Comment by n1ru4l** [comment]
I am also still experiencing the same issues on 6.19.6 😢 (https://github.com/getsentry/sentry-javascript/issues/4731#issuecomment-1103656150)

**Comment by jycouet** [comment]
> Hi @n1ru4l ! I've updated to @envelop/core@^2.3.1, @envelop/sentry@^3.4.0, @sentry/node@^6.19.6, @sentry/tracing@^6.19.6 and it's not causing any runtime errors in my project in the limited testing i've done.
> 
> Version 6.19.4 works as well with the same results.
> 
> Only thing that I'm noticing has changed right now is this log:
> 
> ```
> Sentry Logger [log]: Integration installed: InboundFilters
> Sentry Logger [log]: Integration installed: FunctionToString
> Sentry Logger [log]: Integration installed: ContextLines
> Sentry Logger [log]: Integration installed: Console
> Sentry Logger [log]: Integration installed: OnUncaughtException
> Sentry Logger [log]: Integration installed: OnUnhandledRejection
> Sentry Logger [log]: Integration installed: LinkedErrors
> Sentry Logger [log]: Integration installed: Http
> Sentry Logger [error]: Mongo Integration was unable to require `mongodb` package.
> Sentry Logger [log]: Integration installed: Mongo
> ```
> 
> It's probably not related to this issue, will try to investigate further and open another issue if it's needed.

Did you try adding `npm i mongodb`?
But yes, I think also it' snot linked to this issue.

**Comment by n1ru4l** [comment]
So according to https://github.com/getsentry/sentry-javascript/issues/4731#issuecomment-1126157027, Sentry, unfortunately, shipped a major breaking change in a minor/patch release.

I updated the documentation to reflect that change in https://github.com/n1ru4l/envelop/pull/1407.
