### ISSUE TITLE
[useMaskedErrors] replace EnvelopError with GraphQLError

### ISSUE THREAD

**Issue by n1ru4l** [graphql-hive/envelop#1343]
**Is your feature request related to a problem? Please describe.**

Right now we use `EnvelopError` which extends `GraphQLError` for identifying whether an error should be masked or not.

https://github.com/dotansimha/envelop/blob/7e90676ce7b90a1880d5b06e18b6694819aed1fa/packages/core/src/plugins/use-masked-errors.ts#L17

We choose to use a custom `EnvelopError` because the `GraphQLError` constructor API was cumbersome. We changed this within https://github.com/graphql/graphql-js/pull/3454

Instead of 

```ts
throw new GraphQLError("Oops.", undefined, undefined, undefined, undefined, { code: "SERVER_GOES_BRRT" })
```

We can now instantiate a `GraphQLError` with extensions via the new object constructor overload:

```ts
throw new GraphQLError("Oops.", {
  extensions: { code: "SERVER_GOES_BRRT" },
})
```

**Describe the solution you'd like**

Replace `EnvelopError` with `GraphQLError`. This might be a breaking change though we could potentially work around it by just alias exporting `GraphQLError` as `EnvelopError` 🤔 .

```ts
import { GraphQLError } from "graphql";

export const EnvelopError = GraphQLError
```

However, since the constructor changes that would still be a breaking change.

**Comment by saihaj** [comment]
in engine agnostic envelop https://github.com/n1ru4l/envelop/pull/1487 we dropped `useMaskedError` plugin from `core` since that required relying on `GraphQLError` class. Do we want to create a new plug-in for this?

**Comment by RIP21** [comment]
BTW docs are still outdated and say EnvelopError :)
