### ISSUE TITLE
Masked Errors: Mask errors in all phases

### ISSUE THREAD

**Issue by avaly** [graphql-hive/envelop#1350]
**Describe the solution you'd like**

Currently `useMaskedErrors()` only masks errors thrown in resolvers during the [`execute` phase](https://github.com/dotansimha/envelop/blob/main/packages/core/src/plugins/use-masked-errors.ts#L73-L79).

For security reasons, we'd like to be able to mask all errors in production, including errors thrown in the `parse` and `validate` phases.

I propose adding new options to the plugin that will enable masking errors in the other phases:

```js
useMaskedErrors({
  onParse: true,
  onValidate: true
})
```

**Comment by n1ru4l** [comment]
@avaly Can you elaborate on what your security concerns with errors produced by parse and validate are?

**Comment by avaly** [comment]
All security best practices mention that introspecition should be disabled in production. Yet, an attacker can easily build the schema using the explicit GraphQL errors returned in the `validate` phase, like:

`Cannot query field "foo" on type "User".`

`Field "CreateItem.foo" of required type "String!" was not provided`

**Comment by n1ru4l** [comment]
I think the right solution for this problem would be the usage of persisted operations. Disabling introspection reduces the attack vector, but a GraphQL API would still be vulnerable to brute-force operation building.

A GraphQL API can be public, and masking validation + parse errors there could drastically impact developer productivity. Thus I don't think a GraphQL API should mask those errors and treat them as expected errors.

Having that said, I created https://github.com/dotansimha/envelop/pull/1351. Please let me know whether that works for you.
