### ISSUE TITLE
useLazyLoadedSchema do not support promise

### ISSUE THREAD

**Issue by Moumouls** [graphql-hive/envelop#1381]
**Is your feature request related to a problem? Please describe.**

```js
const server = createServer({
      plugins: [useLazyLoadedSchema(() => this.parseGraphQLSchema.load())]
    })
```

Lazy loading do not support promises.

**Describe the solution you'd like**
Support promises for lazyLoaded schema

**Describe alternatives you've considered**
No alternative found

**Additional context**

**Comment by Moumouls** [comment]
Look strange since because in the docs i see.

```js
async function getSchema({ req }): GraphQLSchema {
  if (req.isAdmin) {
    return adminSchema;
  }

  return userSchema;
}
```

**Comment by Moumouls** [comment]
I see on the master branch

```ts
export const useLazyLoadedSchema = (schemaLoader: (context: Maybe<DefaultContext>) => GraphQLSchema): Plugin => {
  return {
    onEnveloped({ setSchema, context }) {
      setSchema(schemaLoader(context));
    },
  };
};

export const useAsyncSchema = (schemaPromise: Promise<GraphQLSchema>): Plugin => {
  return {
    onPluginInit({ setSchema }) {
      schemaPromise.then(schemaObj => {
        setSchema(schemaObj);
      });
    },
  };
};
```

setSchema seems to expect a GraphQLSchema not a Promise<GraphQLSchema>

**Comment by Moumouls** [comment]
@dotansimha I'm right?

**Comment by Moumouls** [comment]
after some investigation, it seems the source of the issue.

```
Error: Expected {} to be a GraphQL schema.
```

For parse-server we need promise support for useLazyLoadedSchema.

@Urigo

**Comment by n1ru4l** [comment]
I think this is kind of resolved in the next major release we will remove useLazyLoadedSchema
