### ISSUE TITLE
Response cache with GraphQL shield lead to crash

### ISSUE THREAD

**Issue by heddendorp** [graphql-hive/envelop#1395]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

When using the response cache with graphql shield the server can not start.

**To Reproduce**
https://stackblitz.com/edit/node-yvyype?file=src/main.ts
Run `npm dev` on that stackblitz to start the server based on the yoga tutorial.

**Expected behavior**

The server should start

**Environment:**

- Stackblitz

**Additional context**

**Comment by n1ru4l** [comment]
Hey @heddendorp, a fix for this is in the pipeline in https://github.com/dotansimha/envelop/pull/1397 You can already use the release over here: https://github.com/dotansimha/envelop/pull/1397#issuecomment-1130516872

We will release a new version with this fix soon. 😇
