### ISSUE TITLE
The road to making envelop schema-unaware

### ISSUE THREAD

**Issue by n1ru4l** [graphql-hive/envelop#1400]
Currently, envelop is tight-coupled with `GraphQLSchema` and provides specific hooks for replacing/altering the schema (`onResolverCalled`).

We want to envelop to be versatile not only for local schema scenarios but also for remote schemas and allow using envelop as a gateway.

Maybe, envelop should be built around [`executors`](https://www.graphql-tools.com/docs/remote-schemas#creating-an-executor) 🤔 

Required Tasks:
- [ ] refactor plugins that rely on `onResolverCalled`
- [ ] refactor plugins that manipulate/replace the schema
- [ ] ???

**Comment by saihaj** [comment]
I think with `v3` we have addressed this. We removed wrapping of schema, dropped `onResolverCalled` and instead introduced a new `useOnResolve` plugin https://www.the-guild.dev/graphql/envelop/v3/guides/migrating-from-v2-to-v3#2-removed-orchestrator-tracing
