### ISSUE TITLE
useDisableIntrospection - Dynamic enable/disable of introspection is not working

### ISSUE THREAD

**Issue by aylesm** [graphql-hive/envelop#1418]
Hi,

I've been using `useDisableIntrospection` to disable introspection and only expose if a header value is passed to the server.  This works correctly 1st time.  But if I add or remove the header the `disableif` is called correctly.  Looking at the source code there is no mechanism to remove the previous enable/disable and push the new validation rule.  So if you start off disabled you stay disabled.  Or vice-versa.

### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment:**

- OS:
- NodeJS:
- `@envelop/*` versions:
  - `@envelop/core`: `???`

**Additional context**

**Comment by saihaj** [comment]
can you provide a codesandbox for this?

**Comment by n1ru4l** [comment]
Hey @aylesm, can you please provide a reproduction? Are you sure you call `getEnveloped` for each incoming request separately?

**Comment by saihaj** [comment]
file a new issue with reproduction
