### ISSUE TITLE
Drop Node.js version 12

### ISSUE THREAD

**Issue by n1ru4l** [graphql-hive/envelop#1437]
Node.js 12 is no longer in the Maintenance schedule. We should remove it and release a new major version.

_____

- https://nodejs.org/en/about/releases/
- https://github.com/n1ru4l/envelop/pull/1417

**Comment by dimaMachina** [comment]
Don't forget to mention me to add some breaking ESLint rules, like forbid export default and change filenames ;)

**Comment by n1ru4l** [comment]
Yeah sure, it can be a separate pull request, that we can merge before releasing the PR. Can you already create a draft PR of this?

**Comment by dimaMachina** [comment]
I'll do it now
