### ISSUE TITLE
Getting error for "@envelop/statsd" package

### ISSUE THREAD

**Issue by vijayakumarit** [graphql-hive/envelop#1452]
Hi Team,

I am facing an error after installing the package. I just copied any paste the code. the error "Cannot find name 'StatsD'.". I am attaching the screenshot as well.
<img width="1038" alt="Screenshot 2022-07-27 at 12 22 43 PM" src="https://user-images.githubusercontent.com/37203994/181181322-2ae51a04-cd5c-4786-88ea-38fbeca947d5.png">

The error line "const client = new StatsD"

**Comment by n1ru4l** [comment]
This is a documentation issue that is fixed by https://github.com/n1ru4l/envelop/pull/1453.

The import statement for StatsD was missing.

```diff
import { envelop } from '@envelop/core'
import { useStatsD } from '@envelop/statsd'
+import StatsD from 'hot-shots'

const client = new StatsD({
  port: 8020,
  globalTags: { env: process.env.NODE_ENV }
})

const getEnveloped = envelop({
  plugins: [
    // ... other plugins ...
    useStatsD({
      client,
      prefix: 'gql', // results in `gql.operations.count` instead of `graphql.operations.count`,
      skipIntrospection: true // if you wish to disable introspection logging
    })
  ]
})
```
