### ISSUE TITLE
Remove useLazyLoadedSchema

### ISSUE THREAD

**Issue by n1ru4l** [graphql-hive/envelop#1483]
This was a mistake from the beginning as we cannot async set the schema (validate and parse) are sync functions.

**Comment by saihaj** [comment]
I guess we also should remove `useAsyncSchema` since there is nothing `async` about it 🤔

**Comment by n1ru4l** [comment]
@saihaj yes let's remove it, it is borken by design

also related (to be closed)
- https://github.com/n1ru4l/envelop/issues/1110
- https://github.com/n1ru4l/envelop/pull/1382
