### ISSUE TITLE
Let users provide custom `executeFn`

### ISSUE THREAD

**Issue by XiNiHa** [graphql-hive/envelop#1507]
**Is your feature request related to a problem? Please describe**
In the recent work on `graphql-js` for bringing `@defer/stream`, [they introduced a new interface for executing with `@defer/stream`](https://github.com/graphql/graphql-js/pull/3703), which is called `experimentalExecuteIncrementally`. However, [currently there's no way](https://github.com/n1ru4l/envelop/blob/cea2df214e4d598f1206b1e066bf285960011378/packages/core/src/orchestrator.ts#L452) to tell Envelop to use this execution function instead of `execute`.

**Describe the solution you'd like**

Add an option to let users provide their own `executeFn`.

**Describe alternatives you've considered**

Provide an option to enable incremental delivery. I've put this as an alternative only because the incremental execution function has `experimental` at the front of its name, which makes it unreliable to depend on the interface from the library's end.

**Comment by saihaj** [comment]
Hey! We are working on next major release https://github.com/n1ru4l/envelop/pull/1487 which would allow you to pass in custom functions

**Comment by ardatan** [comment]
But I think it is possible currently with `onExecute` hook.
https://github.com/n1ru4l/envelop/blob/cea2df214e4d598f1206b1e066bf285960011378/packages/types/src/hooks.ts#L329

```ts
{
   onExecute({ setExecuteFn }) {
       setExecuteFn(myExecute);
   }
}
```

**Comment by XiNiHa** [comment]
@saihaj lovely 🥰
@ardatan Oh right, just realized that [this reassigns executeFn with custom implementation provided](https://github.com/n1ru4l/envelop/blob/cea2df214e4d598f1206b1e066bf285960011378/packages/core/src/orchestrator.ts#L462), missed that!
