### ISSUE TITLE
ReplaceResolverFn is replacing resolve is mutating field definition

### ISSUE THREAD

**Issue by EmrysMyrddin** [graphql-hive/envelop#1524]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [x] 2. A failing test has been provided
- [x] 3. A local solution has been provided
- [x] 4. A pull request is pending review

---

**Describe the bug**

When implementing a plugin, it is possible to replace the resolver function just before it executed, based an context or any other request information.

The problem is that this replacement is defintive and is persistent over following requests.

**To Reproduce**
Here a dummy example of the bug (dummy because of course, here, we have better ways to pass an authenticated context).
In this example, once an authenticated request have been executed, every non authenticated request would also receive the authenticated context.
```js
const getEnvelop = envelop({
	plugins: {
		onResolverCalled({ context, resolverFn, replaceResolverFn }) {
			if (context.isAuthenticated) return
			replaceResolverFn(
				(...args) => resolverFn(...args, authenticatedContext)
			)
		}
	}
}
```

**Expected behavior**

I expect the resolver function to be reset to it's original implementation for each request since this hook is called for each requests

**Additional context**

My example here is very simple, my actual plugin is doing things that cannot be done in an other way. It's goal is to allow field resolve functions to be generator functions, allowing to use a coroutine library (https://github.com/cuillerejs/cuillere).

You can find the current implementation of the envelop integration here : https://github.com/cuillerejs/cuillere/blob/main/packages/envelop/src/envelop.ts

**Comment by saihaj** [comment]
should be fixed in `v3`  https://www.the-guild.dev/graphql/envelop/v3/guides/migrating-from-v2-to-v3
