### ISSUE TITLE
Plugin useTiming skipIntrospection documentation missing

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [graphql-hive/envelop#1532]
**Describe the bug**

![image](https://user-images.githubusercontent.com/86342787/191513456-cde48661-6bc7-45f8-9ebf-651f6e2a12cf.png)
this is missing in the documentation

**Comment by saihaj** [comment]
hey! in v3 we dropped support for this plugin. You can read more about it here https://www.the-guild.dev/graphql/envelop/v3/guides/migrating-from-v2-to-v3#2-drop-usetiming-plugin
