### ISSUE TITLE
FR: useTiming add skipServiceLookup

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [graphql-hive/envelop#1533]
**Is your feature request related to a problem? Please describe.**

There is already an option for ignoring introspection queries, and now I would like to have one for ignoring ServiceLookups from federated graphs like 
```
Operation execution "__ApolloGetServiceDefinition__" done in 0.2834ms
```

**Comment by saihaj** [comment]
hey! in v3 we dropped support for this plugin. You can read more about it here https://www.the-guild.dev/graphql/envelop/v3/guides/migrating-from-v2-to-v3#2-drop-usetiming-plugin

**Comment by sschneider-ihre-pvs** [comment]
Got it. That currently seems to be the trend with libs. Like apollo server 4 is doing a different thing with removing batteries. It may be a bit inconvenient since that was the only plugin I used, but I much appreciate the effort to make envelop framework or platform agnostic 👍
