### ISSUE TITLE
Unable to use `@envelop/persisted-operations` with GraphQL Yoga

### ISSUE THREAD

**Issue by j0k3r** [graphql-hive/envelop#1575]
**Describe the bug**

We are in the process of migrating away from the abandoned `express-graphql` package to use GraphQL Yoga with Envelop.

I defined the plugin like the documentation says but I always got a `Must provide query string.` error no matter what query I send.
I added log inside the plugin and it seems that the `onParse` method is never called.
I dig higher in GraphQL Yoga and I found that the error is reported by [`useCheckGraphQLQueryParam` -> `onRequestParse` -> `onRequestParseDone`](https://github.com/dotansimha/graphql-yoga/blob/4d63e2b033e25a0fdc7df99bebe329169ed89030/packages/common/src/plugins/requestValidation/useCheckGraphQLQueryParam.ts#L10). `useCheckGraphQLQueryParam` is [called in internally](https://github.com/dotansimha/graphql-yoga/blob/4d63e2b033e25a0fdc7df99bebe329169ed89030/packages/common/src/server.ts#L384) by GraphQL Yoga **before** defined plugins.

Which means, no matter what the `@envelop/persisted-operations` plugin does, it'll be never called because GraphQL Yoga first raise an error. So the plugin doesn't have time to retrieve the document for the given `operationId`.

This seems to have been [refactored this summer](https://github.com/dotansimha/graphql-yoga/pull/1329) (I don't know if it worked before).

In the mean time, I then found a new _unreleased_ plugin from GraphQL Yoga: [`@graphql-yoga/plugin-persisted-queries`](https://github.com/dotansimha/graphql-yoga/pull/1137) but it's really less configurable than the one from Envelop.
That plugin is based on `onRequestParse` instead of `onParse`, so it might actually avoid the `Must provide query string.`.

But that [hooks is experimental](https://github.com/dotansimha/graphql-yoga/issues/1038#issuecomment-1175124790) and seems to only be available for the v3.

Is there a workaround?
Or am I completely wrong somewhere?

**To Reproduce**

- Define a GraphQL server using GraphQL Yoga
- Add and configure the `@envelop/persisted-operations` plugin
- Perform a GET request with an `operationId`

https://stackblitz.com/edit/node-vvqymy?file=index.js

Click on the previous link and then go to `https://node-vvqymy--4000.local-credentialless.webcontainer.io/graphql?operationId=test`.

**Expected behavior**

The server respond with a the result of the persisted query.

**Environment:**

- OS: MacOS
- NodeJS: 16
- `@envelop/persisted-operations` versions: 5.0.3
  - `@envelop/core`: `3.0.3`

**Additional context**

GraphQL Yoga 2.13.13
I don't know if that issue belong to Envelop repo or GraphQL Yoga repo. Let me know.

**Comment by j0k3r** [comment]
I found a workaround.
I created a custom plugin which use `onRequestParse`, sth like:

```js
import { createGraphQLError } from '@graphql-tools/utils'
import queryMap from '../../data/queries/persisted_queries.json'

// shortcut to retrieve PQ from the request and return it (if found)
const getQueryFromPQ = (request) => {
  const [, searchParamsStr] = request.url.split('?')
  const searchParams = new URLSearchParams(searchParamsStr)
  const persistedQueryId = searchParams.get('id') || undefined

  return {
    query: queryMap[persistedQueryId] ?? null,
    persistedQueryId,
  }
}

export const usePersistedQueries = (logger) => ({
  onRequestParse({ request }) {
    const { query, persistedQueryId } = getQueryFromPQ(request)

    if (persistedQueryId) {
      if (!query) {
        logger.error(`Persisted query with id "${persistedQueryId}" is not found`)

        throw createGraphQLError(`Unable to serve persisted query with ID: "${persistedQueryId}"`, {
          extensions: {
            http: {
              status: 404,
              headers: {
                Allow: 'GET',
              },
            },
          },
        })
      }

      logger.info(`Serving persisted query with ID: "${persistedQueryId}"`)

      return {
        onRequestParseDone: function persistedQueriesOnRequestParseDone({ params, setParams }) {
          setParams({
            ...params,
            query,
            operationName: persistedQueryId,
            extensions: {
              persistedQuery: persistedQueryId,
            },
          })
        },
      }
    }

    return {}
  },
})
```

Maybe `@envelop/persisted-operations` should be updated to use `onRequestParse` instead of `onParse`?

**Comment by n1ru4l** [comment]
Hey @j0k3r, for GraphQL Yoga we recommend using the [Yoga Persisted Operation pugin](https://the-guild.dev/graphql/yoga-server/v3/features/persisted-operations) instead.

We are going to release v3 shortly.

I created a PR for updating the docs/plugin page. https://github.com/n1ru4l/envelop/pull/1580

In the future, we definitely want to experiment with introducing an additional phase to envelop - where doing this kind of stuff is possible before the validation phase.
