### ISSUE TITLE
opentelemetry cannot be provided with a globally registered TracerProvider

### ISSUE THREAD

**Issue by jtmthf** [graphql-hive/envelop#1610]
Using `@envelop/opentelemetry`, there's an option to pass a custom provider to it, but it's required that it conforms to `BasicTracerProvider` and not `TracerProvider`. Furthermore I noticed that `@opentelemetry/tracing` is used which has been deprecated in favor of `@opentelemetry/sdk-trace-base`. 

Ideally `@envelop/opentelemetry` would acquire the globally registered tracer through `@opentelemetry/api`.

```ts
import * as opentelemetry from '@opentelemetry/api';

const tracer = opentelemetry.trace.getTracer(serviceName);
```

Alternatively to be a non-breaking change, `trace` should be capable of providing `TracerProvider`.

```ts
import * as opentelemetry from '@opentelemetry/api';

const getEnveloped = envelop({
  plugins: [
    useEngine({ parse, validate, specifiedRules, execute, subscribe }),
    // ... other plugins ...
    useOpenTelemetry(
      {
        resolvers: true, // Tracks resolvers calls, and tracks resolvers thrown errors
        variables: true, // Includes the operation variables values as part of the metadata collected
        result: true // Includes execution result object as part of the metadata collected
      },
      opentelemetry.trace.getTracerProvider()
    )
  ]
})
```

The simplest solution seems to widen the API to accept any `TracerProvider` and to additionally upgrade to use `@opentelemetry/sdk-trace-base`.

**Comment by rcrowe** [comment]
Just got stung by the same thing.

Any chance a contributor can look at https://github.com/n1ru4l/envelop/pull/1611 & point out if there are any further changes required before merging? 🙏🏻
