### ISSUE TITLE
`startTransaction: false` issues warnings

### ISSUE THREAD

**Issue by GauBen** [graphql-hive/envelop#1620]
Hey there!

https://github.com/n1ru4l/envelop/blob/109ae870571f821c20507bcfe9ca2699b4533122/packages/plugins/sentry/src/index.ts#L158-L163

These lines are in the `else` block where the `startTransaction` is set to false.

**Comment by dotansimha** [comment]
@GauBen what version of envelop core and Sentry plugin do you use? and what SDK version of Sentry?
Can you maybe share a reproduction?

**Comment by GauBen** [comment]
Thanks for your help @dotansimha, here are the versions:

- yoga 3.5.1
- envelop/sentry 5.0.0

Reproduction:

```ts
const yoga = createYoga({
  schema,
  context,
  plugins: [
    useSentry({
      startTransaction: false
    }),
  ],
})
```

The warning is printed despite `startTransaction` being false

![image](https://user-images.githubusercontent.com/48261497/216135431-c3f00892-852b-47f9-ad04-17b4ab71b7f0.png)

<details>
<summary>Highlighted inconsistency</summary>
<img width="601" alt="image" src="https://user-images.githubusercontent.com/48261497/216135328-f1bb1f13-0f4a-4caa-96c0-9626982c5289.png">
</details>

**Comment by jeengbe** [comment]
Fixed in https://github.com/n1ru4l/envelop/pull/1632
