### ISSUE TITLE
Response Cache ignoredTypes and ttlPerType don't work when type doesn't have an id field

### ISSUE THREAD

**Issue by mayrn-techdivision** [graphql-hive/envelop#1624]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [x] 2. A failing test has been provided
- [x] 3. A local solution has been provided
- [x] 4. A pull request is pending review

---

**Describe the bug**
- It's not possible to ignore (or set a ttl for) types that either do not have an id field or where the id field is not queried.

**To Reproduce**
- Add a type without an id field to the ignored types parameter of useResponseCache
- Run a query 
=> the result is cached
- Run the query again
=> the response is a cache hit
- Stackblitz repro: https://stackblitz.com/edit/node-wsi6f8?file=test/response-cache.spec.ts

**Expected behavior**
- It's possible to ignore types without an id field or set a ttl for them

**Environment:**

- OS: MacOS
- NodeJS: 18.x
- `@envelop/*` versions:
  - `@envelop/core`: `3.0.4`
  - `@envelop/response-cache`: `4.0.4`

**Additional context**

 We are trying to use the response cache in a graphql mesh setting for an ecommerce project, where some queries do not have ids but are dependent on the currently authenticated customer. I could use the auth header for the cache session to work around that, but that would mean every customer gets their own cached version of all catalog data which defeats the purpose of using the cache in the first place for us.

**Comment by ardatan** [comment]
I'm really impressed how you invested time on this issue by going that deeper from Mesh to Envelop.
I'd love to tweet about it. If it is ok for you, can I ask your Twitter handle?
Thanks!
@mayrn-techdivision

**Comment by mayrn-techdivision** [comment]
Actually had to create one, but I've been planning to do that anyways 😅 it's `@renaissance_dev`
