### ISSUE TITLE
onExecute hooks not called for subscriptions?

### ISSUE THREAD

**Issue by laurisvan** [graphql-hive/envelop#1628]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Our application is leaking memory, and profiling reveals that `executionContextDependencyStore` in GraphQL Modules is growing for every new subscription. In our case, there are many subscriptions where a connection is established with subscriptions, and the subscription (separately or along with connection) is closed without ever executing anything.

When checking the implementation of [graphql modules plugin](https://github.com/n1ru4l/envelop/blob/4eaaf76d418cf56476d57c176ca876fff89a86b2/packages/plugins/graphql-modules/src/index.ts),  it appears that related context cleanup is done in onExecute and onExecuteDone hooks.

In our described case, it appears onExecute is never called. The actual setup is very similar to [graphql-ws example](https://github.com/n1ru4l/envelop/blob/dc1e24b5340ed7eba300a702b17f9be5cff65a8f/examples/graphql-ws/index.ts).

Before providing more exact steps and a canned test case, may I ask is this expected behavior, or have I simply broked our envelop so that execute() is never called? In case of subscriptions, how might I cleanup the graphql-module global map, e.g. as part of onComplete() callback from web socket server?

**To Reproduce**

**Expected behavior**

**Environment:**

- OS: Alpine Linux / MacOS
- NodeJS: 18.x
- `@envelop/*` versions: 2.4.x
  - `@envelop/core`: 2.4.2
  - `@envelop/graphql-modules`: 3.4.2

**Additional context**

**Comment by n1ru4l** [comment]
For subscriptions, `onSubscribe` is called. SO the cleanup there is missing 😓 
Would you like help out and send PR for fixing this?

**Comment by laurisvan** [comment]
@n1ru4l Absolutely! I'll write a quick patch to @envelop/graphql-modules and see how it goes.

**Comment by laurisvan** [comment]
@n1ru4l I hope this one is acceptable. I am not perfectly happy about the test not verifying the actual leak, but I ran out of inspiration on how to verify that easily. At least the added test verifies it does not crash.

We are not in a hurry as we run a patch-package patched version, so if changes are needed, just let me know.
