### ISSUE TITLE
Cannot see some fields in prometheus metrics

### ISSUE THREAD

**Issue by martin-cycle** [graphql-hive/envelop#1631]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [x] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Some prometheus metrics are empty while they shouldn't. With the following plugin configuration:
```
{
      requestCount: true, // requries `execute` to be true as well
      requestSummary: true, // requries `execute` to be true as well
      parse: true,
      validate: true,
      contextBuilding: true,
      execute: true,
      errors: true,
      resolvers: false, // requires "execute" to be `true` as well @WARNING might have a performance impact on GraphQL runtime
      resolversWhitelist: undefined, // reports metrics als for these resolvers, leave `undefined` to report all fields
      deprecatedFields: true,
      registry: register, // If you are using a custom prom-client registry, please set it here
}
```
I would expect to see the execute, the context, the request count histograms as well as the request summary but they appear to be empty (see screenshots below).
<img width="858" alt="Screenshot 2023-02-08 at 17 03 51" src="https://user-images.githubusercontent.com/66952775/217585413-dd89126e-0f42-4e1f-a068-214ff9327ff0.png">
<img width="742" alt="Screenshot 2023-02-08 at 17 04 14" src="https://user-images.githubusercontent.com/66952775/217585420-dfadafbf-f3f8-4168-91bc-c811b56036e0.png">

**To Reproduce**

I am using node.js 16, express-graphql 0.12 and @envelop/prometheus 7.0.4 and @envelop/core 3.0.4 with the configuration described above for the usePrometheus plugin.

**Expected behavior**

I'd expect to see my metrics but only the deprecated field, the parse histogram and the validate histogram appear.

**Comment by ardatan** [comment]
Please share a reproduction on CodeSandbox or StackBlitz. Thanks!

**Comment by martin-cycle** [comment]
Hello @ardatan I just finished to copy my config on StackBlitz and the error keep occuring: https://stackblitz.com/edit/node-g1tdag?file=index.ts

The /graphql route let you do a simple query and the /test route gives you access to the metrics the plugin collects.

Tell me if something is not clear. I am looking into the plugin source code to see if there is something missing.

**Comment by ardatan** [comment]
`contextFactory` is missing here. It is usually needed for the plugin's internals;
https://github.com/n1ru4l/envelop/blob/main/examples/express-graphql/index.ts#L28

```diff
      const {
        parse: customParseFn,
        validate: customValidateFn,
        execute: customExecuteFn,
        schema: envelopedSchema,
+       contextFactory,
      } = sentryEnvelop({
        req: request,
        res: response,
      });

      return {
        schema: envelopedSchema,
        rootValue: root,
+       context: await contextFactory(),
        graphiql: true,
        customParseFn,
        customValidateFn,
        customExecuteFn,
      };
 ```

**Comment by martin-cycle** [comment]
All right! When using only the contextFactory it works on my side but the thing is that I also have a custom context. I guess I can concatenate them but this does not seem to work. I am still investigating but at least I see that this contextFactory was the missing part.

**Comment by ardatan** [comment]
You can pass your your context to `getEnveloped`;
```ts
getEnveloped({ req, res, myStuff })
```
