### ISSUE TITLE
Enable strict type-checking

### ISSUE THREAD

**Issue by PabloSzx** [graphql-hive/envelop#172]
Currently, all this monorepo doesn't have TypeScript's [strict](https://www.typescriptlang.org/tsconfig#strict) type-checking configuration enabled, and this means that it's prone to very common errors and kills a little bit of the objective of using TypeScript, especially since it doesn't even have [strictNullChecks](https://www.typescriptlang.org/tsconfig#strictNullChecks) enabled.

**Describe the solution you'd like**

To enable "strict" in `tsconfig.json`

**Describe alternatives you've considered**

At least start enabling [strictNullChecks](https://www.typescriptlang.org/tsconfig#strictNullChecks), which I'd say is the most important one.

**Comment by dotansimha** [comment]
Done in https://github.com/dotansimha/envelop/pull/173
