### ISSUE TITLE
[sentry]: pointless `skipOperation`

### ISSUE THREAD

**Issue by jeengbe** [graphql-hive/envelop#1720]
https://github.com/n1ru4l/envelop/blob/352c921a83478cfeaede173d77ff6ab3b1114c4a/packages/plugins/sentry/src/index.ts#L109-L112

By default, `skipOperation` is resolves to `isOriginalGraphQLError`, which would always return false for `args`, which is never an error.

**Comment by n1ru4l** [comment]
Can you provide a failing test for this? `skipOperation` is `() => false` by default. 🤔 
 https://github.com/n1ru4l/envelop/blob/352c921a83478cfeaede173d77ff6ab3b1114c4a/packages/plugins/sentry/src/index.ts#L93

**Comment by jeengbe** [comment]
> Can you provide a failing test for this? `skipOperation` is `() => false` by default. 🤔
> 
> https://github.com/n1ru4l/envelop/blob/352c921a83478cfeaede173d77ff6ab3b1114c4a/packages/plugins/sentry/src/index.ts#L93

Hm, right... 🤔 

I must have confused it with `const skipError = pick('skipError', defaultSkipError);` the three times I checked before opening this lol
