### ISSUE TITLE
SHA1.hash is not a function with validation-cache plugin

### ISSUE THREAD

**Issue by tvvignesh** [graphql-hive/envelop#1732]
**Describe the bug**

Hi. I had recently upgraded all dependencies in my server to latest including yoga, envelop plugins, etc. and came up with this error in `validation-cache` plugin which used to work fine before which is visible just when you open GraphiQL.

![image](https://user-images.githubusercontent.com/1165845/220624067-1400d010-745f-40f1-8238-87a55952d7c1.png)

Using the defaults `useValidationCache()` without passing any config.

Currently, I have disabled validationCache plugin because of this issue.

**To Reproduce**
Steps to reproduce the behavior: Use latest deps of envelop, validation-cache, graphql, yoga, etc. and you get this error.

**Expected behavior**

validationCache doesn't throw error like seen above

**Environment:**

- NodeJS: 19.6.1
```
"@envelop/core": "^3.0.6",
"@envelop/depth-limit": "^2.0.6",
"@envelop/graphql-modules": "^4.0.6",
"@envelop/parser-cache": "^5.0.6",
"@envelop/prometheus": "^7.0.6",
"@envelop/response-cache": "^4.0.7",
"@envelop/validation-cache": "^5.1.2",
"@graphql-yoga/render-graphiql": "^3.7.0",
"graphql": "^16.6.0",
"graphql-modules": "^2.1.0",
"graphql-yoga": "^3.7.0",
```

**Comment by ardatan** [comment]
This seems to be a bug
However I don't think you need validation cache plugin since it is builtin in Yoga. Now it uses cached documents from the parser cache with a Yoga specific parser/validation cache plugin.

**Comment by eugene1g** [comment]
Introduced by adding a new dependency `sha1-es` in https://github.com/n1ru4l/envelop/pull/1727  and released as `@envelop/validation-cache@5.1.2` - 

`import SHA1 from 'sha1-es'` does not work in ESM environments. This does work -

```js
import SHA1module from 'sha1-es';
const SHA1=SHA1module.default;
```

A temporary workaround is to pin `@envelop/validation-cache` to `5.1.1`

/paging @n1ru4l

**Comment by n1ru4l** [comment]
@eugene1g Can you send a PR for inlining the dependency?

**Comment by eugene1g** [comment]
@n1ru4l Not a fan of inlining code nobody will ever understand. Can I recommend an alternative library for generating the hash: https://github.com/planttheidea/hash-it It's well-maintained, works in all environments targeted by Envelope, and run 5-10 times faster than `sha1-es`?

**Comment by n1ru4l** [comment]
@eugene1g fine with me
