### ISSUE TITLE
useGenericAuth: Documantation/TypeScript inconsistency

### ISSUE THREAD

**Issue by robertherber** [graphql-hive/envelop#1753]
The [docs here](https://the-guild.dev/graphql/envelop/plugins/use-generic-auth#with-a-custom-validation-function-per-field) shows using `validateUser` as an async function. But when using the latest (5.0.6) version of `@envelop/generic-auth` I get a type validation error when returning a promise from my validateUser function.

Is it meant to work asynchronously or not?

**Comment by EmrysMyrddin** [comment]
It's an error, It's not supposed to be async, since validation graphql-js's validation phase it not async.
You can see this issue discussing about this problem: #1531

**Comment by n1ru4l** [comment]
Hey @robertherber and @EmrysMyrddin, would you like to send a pull request for fixing this mistake?

**Comment by EmrysMyrddin** [comment]
Yes I can work on it :-)
