### ISSUE TITLE
Make @envelop/graphql-jit and @envelop/parser-cache work with async caches

### ISSUE THREAD

**Issue by marhaupe** [graphql-hive/envelop#1888]
**Is your feature request related to a problem? Please describe.**

Both `@envelop/graphql-jit` and `@envelop/parser-cache` (and potentially others as well) don't seem to support caches that return a promise from `cache.get`. Since a lot of production applications that scale out horizontally rely on dedicated caches like Redis or (in our case) Cloudflares' KV, this is a feature a lot of people would benefit from, to the point where I'm not even sure If I'm missing something obvious.

**Describe the solution you'd like**

Looking at the code it should be pretty straightforward. We could substitute every `cache.get` instead with `await cache.get`. `@envelop/response-cache` seems to already handle this by introducing the `PromiseOrValue` wrapper. I'd be open to contributing once I get feedback on this.

**Comment by ardatan** [comment]
The cache in GraphQL JIT keeps a JavaScript object which cannot be serialized and stored in an external storage like Redis or KV.
About parser cache, `parse` in graphql-js is sync so `onParse` is sync as well. That means we cannot use promises in parsing step.

**Comment by marhaupe** [comment]
Ah I see! I knew I was missing something obvious. Thanks for the quick response
