### ISSUE TITLE
useResponseCache with Subscriptions top level field error

### ISSUE THREAD

**Issue by 0-don** [graphql-hive/envelop#1920]
## Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on [Stackblitz](https://stackblitz.com/edit/node-dazht5?file=src%2Fapp.module.ts).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [x] 2. A failing test has been provided
- [x] 3. A local solution has been provided
- [x] 4. A pull request is pending review

---

## Describe the bug

The `onParse` method is adding a `__typename` field to all operations, including subscriptions. This is causing subscriptions to break as they do not expect or handle this field.

```
[
  {
    "message": "Anonymous Subscription must select only one top level field.",
    "extensions": {
      "http": {
        "spec": true,
        "status": 400
      }
    }
  },
  {
    "message": "Anonymous Subscription must not select an introspection top level field.",
    "extensions": {
      "http": {
        "spec": true,
        "status": 400
      }
    }
  }
]
```

## To Reproduce

1. Use the `onParse` method with the provided code.
2. Initiate a GraphQL subscription.
3. Observe that the subscription does not work due to the unexpected `__typename` field.

## Expected behavior

The `onParse` method should not add the `__typename` field to subscriptions, or there should be a way to conditionally skip adding it for certain operations.

## Environment:

- **OS:** Windows
- **NodeJS:** 18
- `@envelop/*` 4:
  - **@envelop/core:** 4

## Additional context

This issue seems to be related to the specific code block that adds the `__typename` field. When commented out, subscriptions work as expected.

**Comment by ardatan** [comment]
Thanks for the PR and the issue! It's fixed in https://github.com/n1ru4l/envelop/pull/1956
