### ISSUE TITLE
[generic-auth] skipped/not included fields are still passed to validate user

### ISSUE THREAD

**Issue by dstoyanoff** [graphql-hive/envelop#1943]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a
     [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on
     [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

When using the plugin with skipped/not included fields, those fields are passed to validate user, which might break the logic. 

In our specific example, we have a custom validate user that would check the user role and if the role is not eligible for the field's permission, we would return an error. That worked great so far. Now however we have a case, where a single field within an object can only be read if the user has a higher access level. For that purpose, we exclude the field from the query if the user doesn't have the permission. The field however still gets passed to validate user and we have no way to detect if we should throw an error or just ignore.

**To Reproduce** Steps to reproduce the behavior:
Example query:
```
query example($id: String!, $canReadEmail: String!) {
  example(id: $id) {
    name
    email @include (if: $canReadEmail)
  }
}
```

in the above query, the name field can be access by all roles, while email can only be accessed by roles that have the read email permission.

**Expected behavior**
Fields with failing `@include` or `@skip` directives should not be passed to validate user

**Environment:**

- OS: macOS
- NodeJS: v18.13.0
- `@envelop/generic-auth` versions: ^5.0.4

**Comment by EmrysMyrddin** [comment]
Hi,

I suppose you mean that `validateUser` function is called for every selected field, even the 'skipped' ones ?

This is not something this plugin is handling for now. You can check for this within your custom `validateUser` function by using `fieldNode` parameter and `shouldIncludeNode` function from `@graphql-tools/utils`:

```ts
function validateUser(params) {
  if (!shouldIncludeNode(params.executionArgs.variableValues, params.fieldNode)) {
    return;
  }

  // Your custom validation here
}
```

Perhaps this is something that the plugin should do automatically. I will make a proposal to discuss about it.

**Comment by dstoyanoff** [comment]
Yeah, this is what I eventually did, but I think it would be cool if the library does this.
