### ISSUE TITLE
Using UnauthenticatedError with Bun causes Segmentation Fault

### ISSUE THREAD

**Issue by robertherber** [graphql-hive/envelop#1952]
**Describe the bug**

When calling `new UnauthenticatedError` bun crashes with Segmentation Fault. My current workaround is to use the "base" GraphQLError from `graphql`.

**To Reproduce** Steps to reproduce the behavior:

1. Use bun (I'm running 1.0.3).
2. Call `new UnauthenticatedError("Some error")`

**Expected behavior**

I expect it not to crash :)

**Environment:**

- OS: MacOS
- Bun 1.0.3
- @envelop/core 4.0.1
- @envelop/generic-auth 6.0.1

**Comment by EmrysMyrddin** [comment]
Hi, thank you for the report :-)

I'm sorry but given the definition of this error very straight forward:

```ts
export class UnauthenticatedError extends GraphQLError {}
```

There is not much we can do about it. Perhaps you should open an issue on bun repo?

**Comment by robertherber** [comment]
@EmrysMyrddin Sounds like a good idea, sorry for clogging :)
