### ISSUE TITLE
@envelop/response-cache clarify handling of null or empty values

### ISSUE THREAD

**Issue by marhaupe** [graphql-hive/envelop#1953]
Recently we've seen some issues with stale data coming from our GraphQL server. It's pretty green field so the general entities involved could be anything, so let's just say we have `Product`, `Query.product` and `Mutation.createProduct`:

```graphql
type Query {
  products: [Product!]!
}

type Mutation {
  addProduct(input: ProductInput!): Product!
}

input ProductInput {
  name: String!
}

type Product {
  id: ID!
  name: String!
}
```

Whenever we handle `createProduct`, we invoke `cache.invalidate([typename: "Product"])`, so every operation related to `Product` would get invalidated - or so we thought. Turns out this only invalidates operations where a `Product` entity has been included in the response. If `Query.products` at some point returned an empty list, the response would not get invalidated on a subsequent `Mutation.createProduct` invocation. An exemplary test in `response-cache.spec.ts` should clarify:

```js
  it('purges cached empty query operation execution result via imperative cache.invalidate api using typename', async () => {
    const spy = jest.fn(() => []);
    let id = 1;
    const schema = makeExecutableSchema({
      typeDefs: /* GraphQL */ `
        type Query {
          products: [Product!]!
        }

        type Mutation {
          addProduct(input: ProductInput!): Product!
        }

        input ProductInput {
          name: String!
        }

        type Product {
          id: ID!
          name: String!
        }
      `,
      resolvers: {
        Query: {
          products: spy,
        },
        Mutation: {
          addProduct(_, { input }) {
            const mockProduct = {
              id: id++,
              name: input.name,
            };
            return mockProduct;
          },
        },
      },
    });

    const cache = createInMemoryCache();
    const testInstance = createTestkit([useResponseCache({ session: () => null, cache })], schema);

    const query = /* GraphQL */ `
      query test {
        products {
          id
          name
        }
      }
    `;

    await testInstance.execute(query);
    await testInstance.execute(query);
    expect(spy).toHaveBeenCalledTimes(1);

    cache.invalidate([{ typename: 'Product' }]);

    await testInstance.execute(query);
    expect(spy).toHaveBeenCalledTimes(2);
  });
```
```
  ● useResponseCache › purges cached empty query operation execution result via imperative cache.invalidate api using typename

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 2
    Received number of calls: 1

      532 |
      533 |     await testInstance.execute(query);
    > 534 |     expect(spy).toHaveBeenCalledTimes(2);
          |                 ^
      535 |   });
      536 |
      537 |   it('variables are used for constructing the cache key', async () => {

      at Object.toHaveBeenCalledTimes (packages/plugins/response-cache/test/response-cache.spec.ts:534:17)
```

Is there a recommended approach to this? I'm tempted to give a fix a try, but it'd rather wait for feedback because it might as well be intended design. Technically, I think we could parse the schema, track which fields have what type and use that to invalidate results with null / empty values.

**Comment by EmrysMyrddin** [comment]
Thank you for your very complete issue report :-)

You are right, the way the plugin is implemented today is based on visiting the result of the query execution instead of the request document. This is because a request can contain abstract types (like unions or interfaces) and the actual type can only be found by visiting the result of the execution.

That's a tradeoff, and I'm not sure which one between abstract types and empty responses are the most commonly found case.

Perhaps we could make our own visitor handling Lists and empty values differently. For now, it is based on `@graphql-tools/utils`'s `visitResult` which just map over the values of the list, meaning we can't react to empty lists.

**Comment by marhaupe** [comment]
I don't want to make empty promises, but if I can make the time it'd like to at least fix it in a way that works for us and monkey patch it via `patch-package`. Would you be open to a contribution or would you rather work on it once you decide if it's worth implementing?
