### ISSUE TITLE
`@envelop/response-cache` not respecting `enabled` being `false`

### ISSUE THREAD

**Issue by klippx** [graphql-hive/envelop#1963]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a minimal reproduction available on [Stackblitz](https://stackblitz.com/edit/node-bat5aq?file=index.js).

---

**Describe the bug**

I am getting cache writes even though enabled is returning false, and debugging things I can see in the source code that `@envelop/response-cache` doesn't consider `enabled()` fn when writing to cache:

```ts
            // THIS IS `false`

            if ((enabled?.(onExecuteParams.args.contextValue) ?? true) === true) {
                const cachedResponse = (await cache.get(cacheKey));
                if (cachedResponse != null) {
                    if (includeExtensionMetadata) {
                        onExecuteParams.setResultAndStopExecution(resultWithMetadata(cachedResponse, { hit: true }));
                    }
                    else {
                        onExecuteParams.setResultAndStopExecution(cachedResponse);
                    }
                    return;
                }
            }
            function maybeCacheResult(result, setResult) {
                processResult(result.data);
                // we only use the global ttl if no currentTtl has been determined.
                const finalTtl = currentTtl ?? globalTtl;
                if (skip || !shouldCacheResult({ cacheKey, result }) || finalTtl === 0) {
                    if (includeExtensionMetadata) {
                        setResult(resultWithMetadata(result, { hit: false, didCache: false }));
                    }
                    return;
                }

                // THIS STILL GETS CALLED

                console.log('maybeCacheResult > cache.set');
                cache.set(cacheKey, result, identifier.values(), finalTtl);
                if (includeExtensionMetadata) {
                    setResult(resultWithMetadata(result, { hit: false, didCache: true, ttl: finalTtl }));
                }
            }
            return {
                onExecuteDone({ result, setResult }) {
                    if (isAsyncIterable(result)) {
                        return handleAsyncIterableResult(maybeCacheResult);
                    }
                    return maybeCacheResult(result, setResult);
                },
            };
```

**To Reproduce** Steps to reproduce the behavior:

1. Visit https://stackblitz.com/edit/node-bat5aq?file=index.js
2. Open /graphql
3. Query `query { hello }`
4. BOOM cache.set is called

**Expected behavior**

When enabled is `false` ALL behaviour in this plugin should be skipped. Especially cache.set / cache.get / cache.invalidate!

**Environment:**

See stackblitz

**Additional context**

N/A

**Comment by EmrysMyrddin** [comment]
@klippx Do you expect the `enabled` function to be called only once ? Or it's not a problem if it is called multiple times ?

**Comment by klippx** [comment]
My 2c when put on the spot would be that since the signature of the function is `enabled?: (request: Request) => boolean;` surely the element of least surprise would be that we would only need one invocation to figure out, since the request won't change at all between different invocations. 

So yea, if you can make it so it is only called once without introducing too much undue complexity that would be great.

In our case we will primarily be using headers retrieved from request context to decide if the request is enabled or not, so I dont think it is a problem _per se_ to call it multiple times. But since each request the yoga server handles will get their own plugin instance it should be safe to memoize the result after the first invocation 🤔
