### ISSUE TITLE
Incompatibility issues with `@apollo/subgraph`

### ISSUE THREAD

**Issue by klippx** [graphql-hive/envelop#1972]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a
     minimal reproduction available on [Stackblitz](https://stackblitz.com/edit/node-psuvdg).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

I am not sure where to attribute this bug, as it requires a very specific setup to trigger. Unfortunately for us, this is exactly our setup in our most important subgraph.

Following the instructions on Yoga site how to integrate Apollo Subgraph https://the-guild.dev/graphql/yoga-server/docs/features/apollo-federation#example-user-service

This works, of course, but when you add a few properties things get interesting:
- Add `DateTime` scalar
- Import `DateResolver` from `graphql-scalars` as a resolver for `DateTime` scalar (yes, that is correct, NOT `DateTimeResolver`)
- Add response cache plugin from `@graphql-yoga/plugin-response-cache`

**To Reproduce** 

1. Go to https://stackblitz.com/edit/node-psuvdg
2. run `node index.js` and you will get `Error: Schema must contain uniquely named types but contains multiple types named "Date".`
3. run `DISABLE_RESPONSE_CACHE=1 node index.js` and realize that if we instead remove response cache this also fixes the issue. But now we dont have a response cache so that is not good.
4. run `DISABLE_DATETIME_RESOLVER=1 node index.js` and realize that removing the Date resolver fixes the issue (but creates bugs in how DateTime is serialized since we want it serialized as DateResolver, this is a fix that contains a breaking change! this is also the reason we cannot use DateTimeResolver (using that also boots everything correctly))

**Expected behavior**

I need this to boot using `node index.js` and 
- having DateTime scalar resolved as Date 
- loading a schema containing federated directives
- having response cache plugin active

**Environment:**

- OS: All
- NodeJS: 18.18
-    "@graphql-yoga/plugin-response-cache": "3.0.0",
-    "graphql": "16.8.1",
-    "graphql-yoga": "5.0.0"

**Additional context**

Since so many components are involved, the issue can be anywhere
- response cache plugin transforming schema using `mapSchema`
- `buildSubgraphSchema` doing something worse that `makeExecutableSchema` would do better  (but I need the federation directives, right?)
- using `DateTimeResolver` instead of `DateTime` but our requirements/expectations are already years on this path so I cant do a breaking change easily. Unfortunately we need `DateTime` to be resolved as DateResolver.

**Comment by klippx** [comment]
Updated stackblitz to latest major versions of everything, the issue persists.

**Comment by EmrysMyrddin** [comment]
After investigation, The problem comes from `@apollo/subgraph` only relying on the config object keys for the scalar names, while `@graphql-tools/schema` is relying on the `name` defined on the type.

This is important because `mapSchema` allows to rename types. For this to work, it needs to update all references to the renamed type. But if the name defined in the type is not correct, it can't remap the old name to the new one.

So you can't really use a scalar resolver with a name `Date` and use it to resolve a scalar named `DateTime`.

An easy workaround that should work is to set the `graphql-scalars` resolver's name to `DateTime`:

```ts
const resolvers = {
  // Create a new Scalar by extending `graphql-scalars` Date config and just change the name.
  DateTime: new GraphQLScalarType({
    ...DateResolver.toConfig(),
    name: 'DateTime',
  }),,
};
```

I've modified your stackblitz to show it working: https://stackblitz.com/edit/node-tzehfw

**Comment by klippx** [comment]
WOw, awesome! Thank you so much ❤️ ❤️ ❤️
