### ISSUE TITLE
useOnResolve allow for introspection types

### ISSUE THREAD

**Issue by darren-west** [graphql-hive/envelop#1981]
### Problem
I am using the useOnResolve plugin to implement some custom functionality around auth, I wanted to be able to apply some custom logic to introspection but found the plugin excludes this.

### Solution
Provide an option to support introspection types, make it disabled by default so it is backwards compatible. 

### Alternatives

I could not use the plugin and do it an alternative way, e.g. mapSchema()

**Comment by EmrysMyrddin** [comment]
Fixed by #1982
