### ISSUE TITLE
`@envelop/apollo-tracing` is throwing `TypeError: Cannot read properties of undefined (reading 'hrtime')`

### ISSUE THREAD

**Issue by Bas950** [graphql-hive/envelop#2007]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a
     [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on
     [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

**To Reproduce** Steps to reproduce the behavior:
1. Go to [codesandbox Reprocuction](https://codesandbox.io/p/sandbox/apollo-tracing-subscriptions-error-th8ycv)
2. Click on _Visit GraphiQL_ 
3. And run the subscription query
4. You will now see an error in the console related to hrtime

**Expected behavior**

It to run the subscription query and countdown from 5 to 0.

**Environment:**

See codesandbox reproduction.

**Additional context**

**Comment by jdolle** [comment]
This looks like a duplicate of https://github.com/n1ru4l/envelop/issues/1771

**Comment by Bas950** [comment]
Copy of https://github.com/n1ru4l/envelop/issues/1771
