### ISSUE TITLE
`@envelop/graphql-jit` is making all subscriptions inputs `undefined` or well `{}`

### ISSUE THREAD

**Issue by Bas950** [graphql-hive/envelop#2008]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a
     [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on
     [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

**To Reproduce** Steps to reproduce the behavior:
1. Go to [codesandbox Reprocuction](https://codesandbox.io/p/sandbox/graphql-jit-subscription-inputs-empty-g336s9)
2. Click on _Visit GraphiQL_ 
3. And run the subscription query
4. You will now see `Oh noes!` in the console.

**Expected behavior**

It to run the subscription query and countdown from 5 to 0.
And no `Oh noes!` in console.

**Environment:**

See codesandbox reproduction.

**Additional context**

**Comment by Bas950** [comment]
Sorry for the @ @n1ru4l, but our development at work is being held up a bit because of this stuff, for now we just don't use `@envelop/graphql-jit` as a workaround.

Is this issue known? and can we expect a fix anytime soon? 
So we can decide if we want to wait or not use `@envelop/graphql-jit` at all.

**Comment by ardatan** [comment]
Like i said here, instead of holding your development, you can focus on debugging the issue further :)
https://github.com/dotansimha/graphql-yoga/discussions/3067#discussioncomment-7301102

**Comment by Bas950** [comment]
Well thank you for your comments, I made some failing tests, and did some debugging, I think it's an issue in [`graphql-jit`](https://github.com/zalando-incubator/graphql-jit), do you wish for me to still create a draft or something with the failing tests?

**Comment by ardatan** [comment]
If it is an issue with graphql-jit, you should create an issue in their repository. We don't maintain that package.
