### ISSUE TITLE
Can no longer use result of `useGenericAuth` to determine if caching should be enabled in response cache plugin

### ISSUE THREAD

**Issue by bryanjswift** [graphql-hive/envelop#2034]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a
     [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on
     [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Previously, a configuration for envelop plugins like the below worked fine, `currentUser` was made available by the `useGenericAuth` plugin at runtime.

```ts
      useGenericAuth({
        contextFieldName: 'currentUser',
        resolveUserFn,
        mode: 'resolve-only',
      }),
      useResponseCache({
        // Disable caching for `Admin` tokens hitting the attendee API (should
        // never happen) and for `ImpersonatedAttendee` tokens.
        // `ImpersonatedAttendee` tokens are intended to be used when
        // previewing content during the authoring experience and so ought to
        // always see the latest view of data.
        enabled: (context: Context) =>
          context.currentUser.role !== 'Admin' &&
          context.currentUser.role !== 'ImpersonatedAttendee',
        // Setting 2000 basically to debounce requests.
        ttl: 2000,
        session: () => null,
      }),
```

The check for whether the `useResponseCache` plugin is enabled in the `onParse` lifecycle function as part of https://github.com/n1ru4l/envelop/pull/1977/commits/b4e1c117e373adcd43fede05475f5387cbfd3db2 means `currentUser` is no longer available in the `enable` function of the `useResponseCache` plugin.

**To Reproduce** Steps to reproduce the behavior:

1. Configure envelop with `@envelop/generic-auth`, and `@envelop/response-cache`
2. Attempt to access the user from the generic-auth plugin in the `enabled` function of the response cache plugin
3. Make any call to the graphql endpoint
4. Observe every result is a 400 response with no error information

Minimal reproduction can be found at https://stackblitz.com/edit/node-3zuq7n

**Expected behavior**

The `currentUser` from `useGenericAuth` should be available in the `enabled` function when it is executed.

**Environment:**

- OS: macOS 14
- NodeJS: v18.17.0
- `@envelop/*` versions:
  -    "@envelop/core": "^5.0.0",
  -    "@envelop/generic-auth": "^7.0.0",
  -    "@envelop/on-resolve": "^4.1.0",
  -    "@envelop/response-cache": "^6.0.0",

**Additional context**

The release notes when new versions of envelop plugins were cut on the GitHub releases page did not include anything about the change for `enabled` in the response cache plugin. Even the change set notes indicating a breaking change in https://github.com/n1ru4l/envelop/pull/1977 do not indicate a change in how parameters are used in the plugin lifecycle.

**Comment by EmrysMyrddin** [comment]
Fixed by #2094
