### ISSUE TITLE
[RFC - New Plugin] Envelop Response Cache Cloudflare KV

### ISSUE THREAD

**Issue by AdiRishi** [graphql-hive/envelop#2055]
## Problem statement
`@envelop/response-cache` already has a great ecosystem, however for those of us building graphql servers on Cloudflare workers, it is invaluable to be able to use the existing tools within the ecosystem. Specifically, Cloudflare KV is an ideal toolset to use for saving response caches as it is a globally distributed low latency KV store.

The goal is to create a package - `@envelop/response-cache-cloudflare-kv` which acts as a companion to `@envelop/response-cache`, allowing users to use Cloudflare KV as a datastore.

## Usage Example
The API exposed by the KV package should closely mirror the existing setup for envelop response cache plugins, e.g the redis cache.
Here is how I envision the KV cache would be setup in a sample worker script
```ts
import { createSchema, createYoga, YogaInitialContext } from 'graphql-yoga';
import { useResponseCache } from '@envelop/response-cache';
import { createKvCache } from 'envelop-response-cache-cloudflare-kv';
import { typeDefs } from './graphql-schema/typeDefs.generated';
import { resolvers } from './graphql-schema/resolvers.generated';

export type Env = {
  GRAPHQL_RESPONSE_CACHE: KVNamespace;
};
export type GraphQLContext = YogaInitialContext & Env & ExecutionContext;

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const kvCache = createKvCache({
      KV: env.GRAPHQL_RESPONSE_CACHE,
      ctx,
      keyPrefix: 'graphql', // optional
    });

    const graphqlServer = createYoga<GraphQLContext>({
      schema: createSchema({ typeDefs, resolvers }),
      plugins: [
        useResponseCache({
          cache: kvCache,
          session: () => null,
          includeExtensionMetadata: true,
          ttl: 1000 * 10, // 10 seconds
        }),
      ],
    });

    return graphqlServer.fetch(request, env, ctx);
  },
};

```

## Considerations for development
One key factor to consider here is how to handle saving and invalidating entity keys within the cache.
Let's take an example from the [blog post](https://the-guild.dev/blog/graphql-response-caching-with-envelop) explaining grapqhql caching.

```
Entity   List of Operation cache keys that reference a entity
User:1   OperationCacheKey1, OperationCacheKey2, ...
User:2   OperationCacheKey2, OperationCacheKey3, ...
User:3   OperationCacheKey3, OperationCacheKey1, ...
```

When saving and invalidating, a naïve approach would be to  save and retrieve a list, essentially creating a map of entity key to operation key. E.g
```ts
// during a set() operation
for (const entity of entities) {
  const entityKey = buildEntityKey(entity.typename, entity.id);
  const existingEntityMap = await config.KV.get<string[]>(entityKey, 'json'); // returns an array of operation keys
  if (!entityMap.includes(operationKey)) {
    entityMap.push(operationKey);
  }
  await config.KV.put(entityKey, JSON.stringify(entityMap));
}

// during an invalidate() operation
const entityKey = buildEntityKey(entity.typename, entity.id);
const entityMap = await config.KV.get<string[]>(entityKey, 'json');
if (entityMap) {
  for (const operationId of entityMap) {
    await config.KV.delete(operationId);
  }
}
await config.KV.delete(entityKey);
```

However, this will lead to race conditions, as KV takes up to 60 seconds to propagate changes across Cloudflare's global network.
This means reading and writing to an array stored in a KV key can lead to some inconsistencies, as only the latest write operation will win.

There are two solutions here
1. Use a synchronisation mechanism like [Cloudflare Durable Objects](https://developers.cloudflare.com/durable-objects/)
2. Flatten the entity map into a list of keys, and using `kv.list({prefix: 'keyPrefix'}` to read all operation keys associated with an entity key.

I've taken approach 2, as it requires less setup from a user using this plugin (in option 1 they would have to also provision a durable object).
This means that instead of storing an entity map of `User:1 => [...arrayOfOperationKeys]` we are storing a list of keys that look like this `['User:1:operationKey', 'User:2:operationKey', ...]`

## Making a PR
I already have a basic implementation of this plugin, I will be working over the next couple of weeks to make it production ready and do a lot of testing
I wanted to ask the maintainers / contributors to this project, would you be willing to accept a PR to create the plugin described above in this project.
Happy to connect / have further discussions on anything that is of concern.

Really looking forward to hearing more. Loved working with envelop and yoga so far, keen to give something back to the ecosystem 😄

**Comment by ardatan** [comment]
PRs are welcome!

**Comment by EmrysMyrddin** [comment]
For reference, there was an existing PR on this subject opened a while ago: https://github.com/n1ru4l/envelop/pull/1761

You can take a look but feel free to open yours with a totally different approach 😀

**Comment by AdiRishi** [comment]
> For reference, there was an existing PR on this subject opened a while ago: https://github.com/n1ru4l/envelop/pull/1761
> You can take a look but feel free to open yours with a totally different approach 😀

Thanks for pointing that out :)
I definitely saw it and took a read, I'm going in a slightly different direction, so it's better for me to write mine from scratch.

I've made a draft PR. Just left some questions there in the discussion as I'm having trouble with the unit tests, would love it if you all could check out my code and help with the questions :)

**Comment by AdiRishi** [comment]
Okay, PR is now ready for review
