### ISSUE TITLE
Prometheus plugin adds undefined label to histograms when label is excluded from config.

### ISSUE THREAD

**Issue by darren-west** [graphql-hive/envelop#2149]
When using the Prometheus plugin for envelop when the configuration options are set to exclude `operationName` or `operationType` the label gets added as undefined rather than excluded. Because of this line [here](https://github.com/n1ru4l/envelop/blob/c0d1fe676b8ebde5db26245b895edc973fc5cd98/packages/plugins/prometheus/src/utils.ts#L107). 

This leaves you with metrics like so 
```
graphql_envelop_phase_execute_bucket{le="0.005",operationName="undefined",operationType="query"} 0
```

That the metric does not have the operationName when it is filtered via config.

**Comment by ardatan** [comment]
Fixed in the latest release! Thanks for the feedback!
