### ISSUE TITLE
Add Sentry v8 compatible integration

### ISSUE THREAD

**Issue by gajus** [graphql-hive/envelop#2193]
Just flagging that the current plugins are not compatible with Sentry v8 SDK.

Some related context:

* https://github.com/getsentry/sentry-javascript/blob/develop/MIGRATION.md#upgrading-from-7x-to-8x
* https://gajus.com/blog/how-to-add-sentry-tracing-to-your-node-js-app}

**Comment by akabekobeko** [comment]
- [sentry-javascript/MIGRATION.md at develop · getsentry/sentry-javascript](https://github.com/getsentry/sentry-javascript/blob/develop/MIGRATION.md#upgrading-from-7x-to-8x)

It looks like need to migrate from `startTransaction` to `startSpan`, which was deprecated in Sentry v8.

```
ERR TypeError: Sentry.startTransaction is not a function
      at onExecute (.../node_modules/@envelop/sentry/cjs/index.js:48:35)
      at .../node_modules/graphql-yoga/node_modules/@envelop/core/cjs/orchestrator.js:360:37
```

**Comment by bgentry** [comment]
Related dep upgrade PR https://github.com/n1ru4l/envelop/pull/2235

Needs some manual work to get it over the line and adjust to the new APIs.

**Comment by trixobird** [comment]
jsut created a new PR [#2277](https://github.com/n1ru4l/envelop/pull/2277), with all the tests passing. I did add a [@ts-expect-error](https://github.com/trixobird/envelop/blob/renovate/major-sentry-javascript-monorepo/packages/plugins/sentry/src/index.ts#L211) though :'(

**Comment by bastiankistner** [comment]
@trixobird wonderful! Was just looking for this 👏

**Comment by trixobird** [comment]
@benjie, @n1ru4l is there anything else needs from my side to get this [PR](https://github.com/n1ru4l/envelop/pull/2277) reviewed and hopefully merged? Apologies for the newbie question

**Comment by klippx** [comment]
@trixobird you should probably update the change-set to `major` since you are removing support for old sentry versions.

**Comment by trixobird** [comment]
@klippx done :)
