### ISSUE TITLE
Envelop Auth0 plugin only accepts a single audience string when it should also accept an array of audiences

### ISSUE THREAD

**Issue by KurtMar** [graphql-hive/envelop#2199]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a
     [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on
     [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [X] 4. A pull request is pending review

---

**Describe the bug**

The Auth0 plugin only accepts a single audience when the underlying jsonwebtoken library also accepts (among others) an array of string and actually internally creates an array from a single audience if provided.

**To Reproduce**

No reproduction.

See jsonwebtoken project for how the property is handled to see that it can in fact receive an array: https://github.com/auth0/node-jsonwebtoken/blob/bc28861f1fa981ed9c009e29c044a19760a0b128/verify.js#L195

Compare to the envelop auth0 plugin:
https://github.com/n1ru4l/envelop/blob/eafae3bf93a19f2e41efcadcc1c42fb99ba08b52/packages/plugins/auth0/src/index.ts#L12

**Expected behavior**

Allow passing an array of strings to the function. Preferably whatever the jsonwebtoken types indicate, which is currently:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/518b9ae4a518c621700a97be30ee128b66a5da78/types/jsonwebtoken/index.d.ts#L60
```typescript
audience?: string | RegExp | Array<string | RegExp> | undefined;
```

**Environment:**

- OS: MacOS
- NodeJS: 20
- `@envelop/*` versions: 
  - `@envelop/core`: `5.0.0`
  - `@envelop/auth0`: `6.0.0`

**Additional context**

NA

**Comment by EmrysMyrddin** [comment]
Fixed by #2200
