### ISSUE TITLE
Add store support to rate-limiter

### ISSUE THREAD

**Issue by deggertsen** [graphql-hive/envelop#2273]
**Is your feature request related to a problem? Please describe.**

We're trying to implement rate-limiting on our graphql-yoga server, but we need the store to use Redis. Currently, it appears that we are simply missing a pass through from the `graphql-rate-limit` package and this should be a simple addition.

**Describe the solution you'd like**

Support the `store` prop on `useRateLimiter` so that Redis can be used as a store option.

**Describe alternatives you've considered**

Go back to using `graphql-rate-limit` and moving away from `graphql-yoga`. Unfortunately, we would lose other features that we need that are included with `graphql-yoga`.

**Additional context**

I've started making the code changes necessary for a PR here:
https://github.com/deggertsen/envelop/blob/feat/add-rate-limiter-store-support/packages/plugins/rate-limiter/src/index.ts
I'm not sure if we also need/want to export the Store and RedisStore types in addition to adding the store prop to `useRateLimiter`.

**Comment by EmrysMyrddin** [comment]
Hi! Thank you for pointing this out :-)

I think that we should just offer the possibility to pass all possible configuration fields to the plugin and forward them to the underlying `graphql-rate-limit` function. I don't see why we should hide those options :-)

As always, PR are very welcome! If you need any help on this, don't hesitate to ask questions here :-)

**Comment by deggertsen** [comment]
I've got the PR created. As a new contributor I felt a bit overwhelmed with all the instructions, especially for a small change like this. I'd appreciate any additional guidance I might need in order to get the PR ready to merge such as if I need to add a change set or bump the version? I figure that's something the maintainers usually do when it's time to make a new release.
