### ISSUE TITLE
`usePrometheus` | PromQL warnings on counter

### ISSUE THREAD

**Issue by klippx** [graphql-hive/envelop#2354]
**Is your feature request related to a problem? Please describe.**

A warning appears in Grafana when graphing counter metrics:

<img width="991" alt="Screenshot 2024-12-20 at 10 37 39 AM" src="https://github.com/user-attachments/assets/2261c6fb-9d4e-4ba3-bda5-e214b0a15cc9" />

I am not sure where this comes from, I cannot find that this is a Prometheus requirement anywhere in [their docs](https://prometheus.io/docs/practices/naming/).

And changing the metric name would be breaking for not only Envelop, but potentially also Yoga and Hive Gateway. But it is something to consider and to open a discussion around.

**Describe the solution you'd like**

Look into if it is worth to rename metrics to follow whatever standards / best practices there is. And link to what standards we are conforming to. 

Right now for whatever reason Grafana whines but it looks like a forwarded error from PromQL (which is not Grafana but Prometheus).

**Describe alternatives you've considered**

I could rename them myself.

**Additional context**

**Comment by EmrysMyrddin** [comment]
Hi!
Yes, this is something we are aware of. It's not mandatory, but part of the recommended naming conventions.
It can of course be safely ignored for now, or you can yourself rename the metric in your plugin configuration.

```ts
usePrometheus({
  metrics: {
    graphql_gateway_subgraph_execute_errors: 'graphql_gateway_subgraph_execute_errors_count',
  }
})
```

We are discussing about what to do for improving this aspect, but we don't think that it's worth the breaking change for now.

We are working on improving the overall story around monitoring/tracing/logging, so it will probably part of this work.
