### ISSUE TITLE
Empty context value in Envelop v0.3.0

### ISSUE THREAD

**Issue by santino** [graphql-hive/envelop#307]
**Describe the bug**
In Envelop 0.3.0 (and the previous alpha releases of this version), the `contextValue` available within the `args` object passed to `onExecute` is empty.  
This eventually breaks some existing plugins, certainly `newrelic` but potentially also `graphql-jit` and `graphql-modules` (since they make use of `contextValue`).  

Any previous version of Envelop (such as latest 0.2.2) are instead properly populating the `contextValue` with GraphQL's document, operation and variables, amongst other properties.

**To Reproduce**
I have created this simple project to reproduce the issue:
https://codesandbox.io/s/envelop-empty-context-z4w75?file=/README.md

The README file contains all instructions to reproduce the issue and compare behaviours of v0.3.0 against v0.2.2

**Expected behavior**
The context value should be populated with GraphQL informations at least, but ideally there should be no difference between how it's populated in v0.2.x vs 0.3.x

**Comment by dotansimha** [comment]
Fixed in `@envelop/core@0.3.1` :)
