### ISSUE TITLE
Allow to extend parser 

### ISSUE THREAD

**Issue by dotansimha** [graphql-hive/envelop#341]
Maybe as something like:

```
onParse({ extendParser }) {
  extendParser("parseFragmentDefinition", (lexer) => {
    // ... lexer ..
  });
}

```

**Comment by saihaj** [comment]
with next major https://github.com/n1ru4l/envelop/pull/1487 user will be able to provide a custom `parse` function and not bound to `graphql-js`'s default `parse`. This allows users to customize however they want to.
