### ISSUE TITLE
Prometheus metrics plugin

### ISSUE THREAD

**Issue by dotansimha** [graphql-hive/envelop#397]

**Comment by dotansimha** [comment]
Available now as `@envelop/prometheus@0.1.0` 🎉

**Comment by kmcrawford** [comment]
@dotansimha how is the scrape /metrics configured and get results?

**Comment by dotansimha** [comment]
> @dotansimha how is the scrape /metrics configured and get results?

Hi @kmcrawford ,
This plugin only depends on `prom-client`, you can hook an existing instance to get the GraphQL stats. 
For the actual scraping, you need to connect it to your server and expose the `prom-client` instance. Usually, it's as simple as listening to `/metrics` endpoint and returning the value of `registery.metrics()` result.
