### ISSUE TITLE
Export testkit utils from @envelop/testing

### ISSUE THREAD

**Issue by klippx** [graphql-hive/envelop#438]
**Is your feature request related to a problem? Please describe.**

For building custom plugins I was checking how you write specs. And you import a lot of nifty stuff from @envelop/testing. However this seems not to be accessible from userland. What is the suggested approach?

**Describe the solution you'd like**

I would like to be able to import stuff from @envelop/testing:

`import { createTestkit } from '@envelop/testing'`

**Describe alternatives you've considered**

None. It must be supported by the @envelop itself, there's no point for users to go deep and mock internals.

**Additional context**

None

**Comment by dotansimha** [comment]
Thank you for creating this @klippx , you are right. I'm thinking about the way to export it - it could be either a package (like it's today) or as an export from `core` package. @n1ru4l thoughts?

**Comment by n1ru4l** [comment]
@dotansimha I would prefer this to be a standalone package. I would not like to have unused test code included in a package i install for production usage.
