### ISSUE TITLE
Support for Mercurius

### ISSUE THREAD

**Issue by nghiepdev** [graphql-hive/envelop#467]
Hey,
 [Mercurius](https://github.com/mercurius-js/mercurius) and `Fastify` are being favored over `Apollo server`.
 
 So you can make an example of how to `envelop` implement with `Mercurius` and `Nexus`
 
 Thank you in advance.

**Comment by Urigo** [comment]
@nghiepit let's say to take [this example](https://github.com/dotansimha/envelop/tree/main/examples/graphql-helix) and use it with `Nexus`, what then is missing for you that Mercurous has?

**Comment by nghiepdev** [comment]
@Urigo I'm not sure. `Mercurius` just that it has quite a few features that interest me and simplified configuration with me.

**Comment by PabloSzx** [comment]
GraphQL EZ is an ongoing project (not released yet, but completely usable, and already used in production) that uses Envelop in it's core and does what Mercurius does, visit https://www.graphql-ez.com/ for more information @nghiepit 

You can also check the EZ plugin hub https://www.graphql-ez.com/plugins for some of the current features that are available through plugins

**Comment by nghiepdev** [comment]
@PabloSzx Wow thank you so expect.
