### ISSUE TITLE
Possible typo in useRateLimiter example code

### ISSUE THREAD

**Issue by hitochan777** [graphql-hive/envelop#485]
**Describe the bug**

This is not a bug but a typo in a example code (I didn't know what template to use, sorry)

[The example code for useRateLimiter](https://github.com/dotansimha/envelop/blob/adca399f700978f47969d75f96382fc030bde30d/packages/plugins/rate-limiter/README.md) imports wrong package name `@envelop/generic-auth'`.
Shouldn't it be `@envelop/rate-limiter` instead?

**Comment by n1ru4l** [comment]
@hitochan777 You wanna send a pr to fix this? 😊
