### ISSUE TITLE
[Feature Request]: Pass data from onEnvelop to parser

### ISSUE THREAD

**Issue by ccollie** [graphql-hive/envelop#581]
**The Problem**
I'm working on a plugin for Apollo compatible `automatic persisted queries` ([issue](https://github.com/dotansimha/envelop/issues/496)), but it's not possible in a clean way with the current architecture. Specifically, the protocol allows for the graphql `query` field to be `undefined` if the persisted query extension is present in the request.

https://github.com/apollographql/apollo-link-persisted-queries#apollo-engine

In `envelop`, `onParse` expects a non-empty `params.source`, so the only opportunity to intercept is in `onEnvelop`. For automatic persisted queries, we lookup queries by hash which we need to provide to the parser. However, there's no way of passing along information between `init` and `parse`.

**Describe the solution you'd like**
Add `setQuery`/`setSource` or `setParsedDocument` to `OnEnvelopedHookEventPayload`, and the ability to pass the change on to the parser.

**Describe alternatives you've considered**
An `after` hook for `onEnvelop`.

**Comment by ccollie** [comment]
Thinking more about this, maybe an optional `preParse` hook would be the most low-impact way of handling this.

**Comment by ccollie** [comment]
According to @PabloSzx, this is a higher level concern. Moving to `graphql-ez`

**Comment by dotansimha** [comment]
@ccollie You can also use the shared context object that `envelop` creates when you call `getEnveloped` function, and extend it with a custom object you can later use. 

The payload for `onEnveloped` has this params: 
https://github.com/dotansimha/envelop/blob/main/packages/types/src/hooks.ts#L64-L77

You can use it with a custom symbol if you want to store internal/private data and use it later:

```ts
const mySymbol = Symbol('mySymbol');

const plugin = {
  onEnveloped({ extendContext }) {
    extendContext({ [mySymbol]: 'MyCustomData' });
  },
  onParse({ context }) {
    const myData = context[mySymbol]; // will be MyCustomData
  }
}

```

**Comment by ccollie** [comment]
@dotansimha the issue is that what I'm attempting cannot be self-contained in `envelop` itself. In other words, `parse` expects a valid non-null query which is passed externally (ex. from an `http` request). We're trying to automagically intercept an undefined query and substitute it before it's parsed.

  After thinking about it, it seems to be a higher level concern, and seems impractical unless we allow plugins to wrap the `parse` function.
