### ISSUE TITLE
useSentry: Should not report instances of EnvelopError

### ISSUE THREAD

**Issue by n1ru4l** [graphql-hive/envelop#634]
EnvelopErrors are expected errors and should not be reported.

**Comment by saihaj** [comment]
we no longer have `EnvelopError` and sentry plugin from now on will skip sending `GraphQLError` https://www.the-guild.dev/graphql/envelop/v3/guides/migrating-from-v2-to-v3#1envelopsentry-default-will-skip-all-graphqlerror
