### ISSUE TITLE
useParserCache - cache.get() is called multiple times

### ISSUE THREAD

**Issue by dios-david** [graphql-hive/envelop#720]
**Describe the bug**

It's just a potential performance issue that `cache.get()` is always called twice:
```ts
if (documentCache.get(key)) { // 1.
  const document = documentCache.get(key); // 2.

  if (document) {
    setParsedDocument(document);
  }
}
```

This can lead to unnecessary slowdown with large caches where the lookup can be slower.

**To Reproduce**

Use `useParserCache` plugin.

**Expected behavior**

`cache.get()` should only be called once per request.

**Comment by dotansimha** [comment]
Awesome catch, thanks @dios-david !
