### ISSUE TITLE
Use existing cache instances in useParserCache and useValidationCache

### ISSUE THREAD

**Issue by dios-david** [graphql-hive/envelop#740]
**Is your feature request related to a problem? Please describe.**

It would be useful to pass in existing cache instances to `useParserCache` and `useValidationCache`.
This would open the possibility to:
- pass in custom cache implementations (if that implements the usual get/set/clear methods) as currently only `tiny-lru` is supported
- set up custom monitoring of cache sizes and hit ratios
- re-use same caches in multi-envelop setups

**Describe the solution you'd like**

Support passing in cache instances to `useParserCache` and `useValidationCache`.

**Describe alternatives you've considered**

Technically speaking it would be possible to expose the cache instance created by the plugins, but the implementation of that would be quite complex imo.
Also, that would not solve using non-LRU implementations.

**Comment by dotansimha** [comment]
This is a great idea. @dios-david do you want to create a PR for adding that?

**Comment by dios-david** [comment]
> This is a great idea. @dios-david do you want to create a PR for adding that?

Thanks, I already opened it :) https://github.com/dotansimha/envelop/pull/741
