### ISSUE TITLE
resource-limitations: Accept custom types for connection arguments

### ISSUE THREAD

**Issue by avaly** [graphql-hive/envelop#815]
**Is your feature request related to a problem? Please describe.**

We currently use a custom scalar type which extends the `Int` type to allow us to define the documentation of the parameter in all our connection types.

It seems that this plugin expects `first` and `last` arguments to be only of `Int` type.

**Describe the solution you'd like**

An option should be accepted by the plugin to customize the type of these arguments.

**Additional context**

See: https://github.com/dotansimha/envelop/blob/main/packages/plugins/resource-limitations/src/index.ts#L28-L30

**Comment by dotansimha** [comment]
Available in `@envelop/resource-limitations@0.2.0`. Thanks!
