### ISSUE TITLE
resource-limitations: Custom min/max values for connection arguments

### ISSUE THREAD

**Issue by avaly** [graphql-hive/envelop#816]
**Is your feature request related to a problem? Please describe.**

We use custom values for the min/max values of the connection arguments.

**Describe the solution you'd like**

Add options for customizing the min/max of the `first` and `last` arguments in the connection types.

**Additional context**

See: https://github.com/dotansimha/envelop/blob/main/packages/plugins/resource-limitations/src/index.ts#L98-L114

**Comment by n1ru4l** [comment]
@avaly Are you interested in sending a PR for implementing this?

**Comment by dotansimha** [comment]
Available in `@envelop/resource-limitations@0.2.0`. Thanks!
