### ISSUE TITLE
Upgrade Yarn to v3 ?

### ISSUE THREAD

**Issue by EmrysMyrddin** [graphql-hive/envelop#874]
**Is your feature request related to a problem? Please describe.**

Yarn v1 is in security maintenance mode only since few years now.

Yarn v2 offers new feature with better support of workspaces and more stable dependency resolver.

Is the migration to yarn v2/3 something you want ? If so, I can give a try to upgrade, I have recently done the migration on multiple repositories.

**Describe the solution you'd like**

You surely know that the main pain point in upgrading to V2 is PnP being the default linker.

The easier way to upgrade is to use the node_modules linker. This removes any imcompatibility (like with TypeScript).

**Comment by dotansimha** [comment]
Sounds good! I agree that v3 should be better and simpler to use (i guess without PnP). I'm also fine with experimenting with `pnpm`. 
@EmrysMyrddin what do you think? Any chance you want to try it and create a PR? :)

**Comment by EmrysMyrddin** [comment]
I will try to make a PR with yarn V3 :)

Just hope it will not have stange end cases with your other tools like the one used for versioning and building. Will see !

**Comment by n1ru4l** [comment]
We are quite happy with yarn v1 right now.
