### ISSUE TITLE
New plugin: `useDebugLogger`

### ISSUE THREAD

**Issue by dotansimha** [graphql-hive/envelop#975]

**Comment by YassinEldeeb** [comment]
Hey @dotansimha, can you please provide more context on what should the plugin do in contrast of the existing [`useLogger`](https://the-guild.dev/graphql/envelop/plugins/use-logger) plugin?

**Comment by dotansimha** [comment]
> Hey @dotansimha, can you please provide more context on what should the plugin do in contrast of the existing [`useLogger`](https://the-guild.dev/graphql/envelop/plugins/use-logger) plugin?

I think this was an old idea, and probably no longer relevant

**Comment by YassinEldeeb** [comment]
oh, thanks for clarifying!
